apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paymentservice
  namespace: api
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`newstars.api.com`) 
    kind: Rule
    services:
    - kind: Service
      name: payment-service
      namespace: api
      port: 80

# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: name-example-foo
#   namespace: default
# spec:
#   virtualhost:
#     fqdn: foo1.bar.com
#   routes:
#     - match: /
#       services:
#         - name: s1
#           port: 80