apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payment-service
  namespace: api
  labels:
    app:  payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app:  payment-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/data/postgres/config"
        vault.hashicorp.com/role: "postgres"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "secret/data/postgres/config" -}}
            export DB_URL="postgres://{{ .Data.data.POSTGRES_USER }}:{{ .Data.data.POSTGRES_PASSWORD  }}@10.42.2.15:5432/{{ .Data.data.POSTGRES_DB  }}"
          {{- end -}}
    spec:
      serviceAccountName: postgres
      containers:
      - name:  payment-service
        image:  alhon05/gosimplecrud:v15
        command: ['/bin/bash', '-c']
        args: ['source /vault/secrets/database-config.txt && /app/main']
        ports:
        - containerPort: 4005
        env:
          - name: PORT
            value: "4005"
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: api
spec:
  selector:
    app: payment-service
  # Should be typed ClusterIP - NodePort if you want to bypass the ingress and fortforward the traffic to the desired port just for testing purposes only
  # Port forward using  - kubectl port-forward pod/pod-name 4005:4005
  type: ClusterIP   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4005
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: api
  labels:
    app: postgres
