apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payment-service
  namespace: api-services
  labels:
    app:  payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app:  payment-service
    spec:
      containers:
      - name:  payment-service
        image:  alhon05/gosimplecrud:v9
        ports:
        - containerPort: 4005

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: api-services
spec:
  selector:
    app: payment-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4005
