
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres_db
spec:
  replicas: 2
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.4-alpine3.18
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: secret
          ports:
            - containerPort: 5432
              name: postgres  
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim