---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
data:
  users: YWRtaW46JGFwcjEkbGlHbUlOdjgkbDFTYi9yS21QVThKS05Iak51VXZwLgoK

# user: admin, password: newstarsinc

