---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-persistent-vol
  namespace: database
  labels:
    type: local
spec:
  storageClassName: pg-managed-nfs-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  nfs:
    path: /shared/postgres_data
    server: 172.24.31.52
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-nfs-pvc
  namespace: database
spec:
  storageClassName: pg-managed-nfs-storage
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 1Gi