apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        ports:
          - containerPort: 80
            name: pgadminport
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "pgadmin@newstars.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "secret"
          - name: PGADMIN_PORT
            value: "80"
        # env:
        #   PGADMIN_DEFAULT_EMAIL: "pgadmin@newstars.com"
        #   PGADMIN_DEFAULT_PASSWORD: "secret"
        #   PGADMIN_PORT: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - port: 80
      nodePort: 30200
