---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.4-alpine3.18
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-persistent-vol
              mountPath: /var/lib/postgresql/data
      volumes:                                     
      - name:  pg-persistent-vol
        persistentVolumeClaim:
          claimName: pg-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  postgres-service
  namespace: database
spec:
  type: ClusterIP
  selector:
    name:  postgres
  ports:
  - protocol: TCP
    port:  5432
    targetPort:  5432



