---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # serviceAccountName: postgres
      containers:
        - name: postgres
          image: postgres:15.4-alpine3.18
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "secret"
          volumeMounts:
            - name: pg-persistent-vol
              mountPath: /var/lib/postgresql/data
      volumes:                                     
      - name:  pg-persistent-vol
        persistentVolumeClaim:
          claimName: pg-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  postgres-service
  namespace: database
spec:
  type: ClusterIP
  selector:
    name:  postgres
  ports:
  - name: postgres
    protocol: TCP
    port:  80
    targetPort:  5432
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: postgres
#   namespace: database
#   labels:
#     app: postgres