apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-config
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # mypassword
  POSTGRES_PASSWORD: c2VjcmV0clear