apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  creationTimestamp: "2023-10-11T06:08:00Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-d4073277-f0d7-45a3-887a-4d0936664a33
  resourceVersion: "30275"
  uid: a39faf68-e733-4660-803d-2eaaaeb4a866
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-hashicorp-consul-consul-server-0
    namespace: hashicorp
    resourceVersion: "30140"
    uid: d4073277-f0d7-45a3-887a-4d0936664a33
  hostPath:
    path: /var/lib/rancher/k3s/storage/pvc-d4073277-f0d7-45a3-887a-4d0936664a33_hashicorp_data-hashicorp-consul-consul-server-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - agent
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: agent
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2023-10-11T06:07:50Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: consul
    chart: consul-helm
    component: server
    hasDNS: "true"
    release: consul
  name: data-hashicorp-consul-consul-server-0
  namespace: hashicorp
  resourceVersion: "30277"
  uid: d4073277-f0d7-45a3-887a-4d0936664a33
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-d4073277-f0d7-45a3-887a-4d0936664a33
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound