---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: consul-pv
  namespace: hashicorp
  labels:
    type: local
spec:
  storageClassName: managed-nfs-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  nfs:
    path: /shared/consul_data
    server: 172.24.31.50
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-hashicorp-consul-consul-server-0 
  namespace: hashicorp
spec:
  storageClassName: managed-nfs-storage
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 4Gi