apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  # change this based on the namespace you created specifically for NFS provision deployment
  namespace: hashicorp
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner-runner
  namespace: hashicorp
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client-provisioner
  namespace: hashicorp
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    # change this based on the namespace you created specifically for NFS provision deployment
    namespace: hashicorp
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner
  # change this based on the namespace you created specifically for NFS provision deployment
  namespace: hashicorp
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner
  # change this based on the namespace you created specifically for NFS provision deployment
  namespace: hashicorp
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    # change this based on the namespace you created specifically for NFS provision deployment
    namespace: hashicorp
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io