---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-persistent-vol
  namespace: hashicorp
  labels:
    type: local
spec:
  storageClassName: managed-nfs-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  nfs:
    path: /shared/consul_data
    server: 172.24.31.50
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-hashicorp-consul-consul-server-0
  namespace: hashicorp
spec:
  storageClassName: managed-nfs-storage
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-hashicorp-consul-consul-server-1
#   namespace: hashicorp
# spec:
#   storageClassName: managed-nfs-storage
#   accessModes:
#    - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: data-hashicorp-consul-consul-server-2
#   namespace: hashicorp
# spec:
#   storageClassName: managed-nfs-storage
#   accessModes:
#    - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi